name: Transafe Deploy to server

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14.x'

    - name: Install dependencies
      run: npm install       

    - name: Build the app
      run: npm run build
    
    - name: Print directory contents
      run: ls -la dist/

    - name: Deploy
      uses: easingthemes/ssh-deploy@v2.1.5
      with:
        command: |
          rsync -ravz --delete --exclude='.git/' --exclude='node_modules/' ./dist/ REMOTE_USER@REMOTE_IP:/
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        REMOTE_IP: ${{ secrets.REMOTE_IP }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}



    - name: Debugging
      uses: appleboy/ssh-action@v2
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          echo "SSH connection successful"
          ls -la /var/www/TranSafe-Frontend/Render/
