name: Transafe Deploy to server

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14.x'

    - name: Install dependencies
      run: npm install       

    - name: Build the app
      run: npm run build
    
    - name: Print directory contents
      run: ls -la dist/

    - name: Deploy
      uses: easingthemes/ssh-deploy@v2.1.5
      with:
        command: |
          rsync -rav --delete --exclude .git --exclude node_modules --exclude .github --exclude .gitignore /home/runner/work/TranSafe-Frontend/TranSafe-Frontend/ ubuntu@54.219.53.71:/home/ubuntu/
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        



    - name: Debugging
      uses: appleboy/ssh-action@v0.1.6
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        host: "54.219.53.71"
        username: "ubuntu"
        port: 22
        script: |
          echo "SSH connection successful"
          ls -la /var/www/TranSafe-Frontend/Render/
