name: Deploy

on:
  push:
    branches:
      - main

env:
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY  }}

jobs:
  set_args:
    runs-on: ubuntu-latest
    steps:
      - name: Set ARGS
        id: set_args
        run: echo "::set-output name=args::'-t \"sudo rm -rf /var/www/TranSafe-Frontend/dist/*\" -t \"mkdir -p /var/www/TranSafe-Frontend/dist && exit\" -t \"sudo cp -r $SOURCE/* /var/www/TranSafe-Frontend/dist/\"'"

  deploy:
    runs-on: ubuntu-latest
    needs: set_args
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install rsync
        run: sudo apt-get install -y rsync

      - name: Deploy over SSH
        uses: easingthemes/ssh-deploy@v2
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USERNAME }}
          args: ${{ steps.set_args.outputs.args }}
          local_dir: dist/
          remote_dir: /var/www/TranSafe-Frontend/
          exclude: '.git/*,node_modules'
