name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: npm install

    - name: Build the Project
      run: npm run build

    - name: Run rsync deploy action
      uses: easingthemes/ssh-deploy@v3.0.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        REMOTE_USER: ${{ secrets.REMOTE_USERNAME }}
        args: -rltgoDzvO --delete --exclude=node_modules --exclude=.git --exclude=dist --exclude=.* --exclude=_* /home/runner/work/TranSafe-Frontend/TranSafe-Frontend/dist/ REMOTE_USER@REMOTE_HOST:/var/www/TranSafe-Frontend/

    - name: Log rsync output
      run: echo "${{ steps.rsync.outputs.stdout }}"

    - name: Check rsync status
      run: |
        if [ ${{ steps.rsync.outputs.status }} -eq 0 ]; then
          echo "Deployment successful"
        else
          echo "Deployment failed"
        fi
