name: Deploy

on:
  push:
    branches:
      - main

env:
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
  REMOTE_USER: ${{ secrets.REMOTE_USERNAME }}
  REMOTE_PATH: "/var/www/TranSafe-Frontend/"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install rsync
        run: sudo apt-get -y install rsync
      - name: Deploy over SSH
        uses: easingthemes/ssh-deploy@v3.1.1
        with:
          ssh-private-key: ${{ env.SSH_PRIVATE_KEY }}
          run: |
            echo "✅️ [CLI] Rsync exists"
            which rsync
            echo "[Rsync] Starting Rsync Action: ${GITHUB_WORKSPACE} to ${env.REMOTE_USER}@${env.REMOTE_HOST}:${env.REMOTE_PATH}"
            echo "[Rsync] excluding folders "
            echo "- node_modules"
            echo "- .git"
            echo "- dist"
            echo "- .*"
            echo "- _*"
            rsync -azv --delete --exclude=node_modules --exclude=.git --exclude=dist --exclude=.* --exclude=_* ${GITHUB_WORKSPACE}/ ${env.REMOTE_USER}@${env.REMOTE_HOST}:${env.REMOTE_PATH} --rsync-path="sudo rsync"
            exit_status=$?
            if [ $exit_status -eq 0 ]; then
              echo "✅️ [Rsync] completed successfully."
            else
              echo "❌ [Rsync] error: rsync exited with code $exit_status"
              exit $exit_status
            fi
